// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pntuzzcdkyezfnqiedgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBudHV6emNka3llemZucWllZGd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNDkyNDUsImV4cCI6MjA3MTcyNTI0NX0.PFLig2hQzYDtQTNjFOkcQBUG6ELgzwz3dWLTLi4kXBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});